#!/bin/bash

# Copyright 2009 The GoGo Authors. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

#
# This tool can test against predefined source files by comparing various
# compiled results. New valid sets can be generated and need to be 
# acknowlegded before code can be tested against.
#

# change to this directory for easier handling of paths
SELF="test.sh"
BASEDIR=`dirname $0`
cd $BASEDIR

# tools that are used
SHA256SUM=/usr/bin/sha256sum

# configuration
TESTDIR="tests"
TMPDIR="tmp"
GOGODIR=../src
GOGO=$GOGODIR/gogo

# Performs internal checks to make sure everything is set up.
function do_checks() {
    echo "---------------------------------------------------------------------\
-----------"
    echo "Performing internal checks"
    echo "---------------------------------------------------------------------\
-----------"

    echo -n "Checking for sha256sum tool... "
    if [ -e $SHA256SUM ]; then
        echo "ok"
    else
        echo "failed"
        exit 1
    fi

    echo -n "Checking for gogo compiler... "
    if [ -e $GOGO ]; then
        echo "ok"
    else
        echo "failed"
        exit 1
    fi  

    echo -n "Checking for $TESTDIR... "
    if [ -d $TESTDIR ]; then
        echo "ok"
    else
        echo "failed"
        exit 1
    fi  

    echo -n "Checking for $TMPDIR... "
    if [ -d $TMPDIR ]; then
        echo "ok"
    else
        mkdir -p $TMPDIR
        echo "creating it"
    fi    
}

# Generates new results that can be marked as valid
function new_valids() {
    do_checks

    if [ -e valid_results ]; then
        echo "Removing valid_results... ok"
        rm valid_results
    fi  
    if [ -e valids_acked ]; then
        echo "Removing valids_acked... ok"
        rm valids_acked
    fi

    echo "---------------------------------------------------------------------\
-----------"
    echo "Generating new valid results"
    echo "---------------------------------------------------------------------\
-----------"
    for filename in $( ls $TESTDIR )
    do
        $GOGO $TESTDIR/$filename > $TMPDIR/$filename.tmp
        result=$($SHA256SUM $TMPDIR/$filename.tmp)
        echo "$result"
        echo "$result" >> valid_results
    done

    if [ -d $TMPDIR ]; then
        echo "Removing $TMPDIR... ok"
        rm -r $TMPDIR
    fi
}

# Acknowledges the previously generated results
function ack_valids() {
    if [ -e valid_results ]; then
        echo "-----------------------------------------------------------------\
---------------"
        echo "Acknowledging the generated results"
        echo "-----------------------------------------------------------------\
---------------"
        touch valids_acked    
    else
        echo "No last valid results found. Run './test newvalids' to generate \
them"
        exit 1 
    fi
}

# Performs a checksum comparison against the previously acked results
function do_tests() {
    do_checks
    if [ -e valids_acked ]; then
        echo "-----------------------------------------------------------------\
---------------"
        echo "Performing tests against last valid results"
        echo "-----------------------------------------------------------------\
---------------"
        for filename in $( ls $TESTDIR )
        do
            $GOGO $TESTDIR/$filename > $TMPDIR/$filename.tmp
        done
        $SHA256SUM -c valid_results
    else
        echo "-----------------------------------------------------------------\
---------------"
        echo "No last acknowlegded valid results found. Run './test newvalids' 
and './test ackvalids' to generate and acknowledge them."
        exit 1
    fi
}

# Removes all temporary files (except the valid_results checksum file)
function do_clean() {
    echo "---------------------------------------------------------------------\
-----------"
    echo "Cleaning"
    echo "---------------------------------------------------------------------\
-----------"

    echo -n "Removing $TMPDIR... "
    if [ -d $TMPDIR ]; then
        rm -r $TMPDIR
        echo "ok"
    else
        echo "not needed"

    fi 
    if [ -e valids_acked ]; then
        echo "Removing valids_acked... ok"
        rm valids_acked
    fi
}

# Prints the help (little howto)
function do_help() {
    echo "---------------------------------------------------------------------\
-----------"
    echo "GoGo testsuite"
    echo "---------------------------------------------------------------------\
-----------"
    echo "To generate new results run './test newvalids'"
    echo "To acknowlegde them run './test ackvalids'"
    echo "To test against acked results run './test test'"
}

case $1 in
    newvalids)
        new_valids
        ;;
    ackvalids)
        ack_valids
        ;;
    test)
        do_tests
        ;;
    clean)
        do_clean
        ;;
    help)
        do_help
        ;;
    *)
	    echo "Usage: $SELF {newvalids|ackvalids|test|clean|help}" >&2
        ;;
esac
exit 0
        
