# Copyright 2009 The GoGo Authors. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=libgogo
GOFILES=\
        libgogo.go
OFILES=\
        asm_$(GOOS)_$(GOARCH).$O

include $(GOROOT)/src/Make.pkg
