# Copyright 2009 The GoGo Authors. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=gogo
GOFILES=\
    gogo.go\
    scanner.go\
    token.go\
	parser.go

include $(GOROOT)/src/Make.cmd
